### ISSUE TITLE
Client-Side Exception 

### ISSUE THREAD

**Issue by farkon00** [peterhanania/Discord-Package#20]
After importing a package i got two `DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.` exceptions.
Tracebacks:
```
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at hg (https://discordpackage.com/_next/static/chunks/framework-9b5d6ec4444c80fa.js:11:94139)
    at hi (https://discordpackage.com/_next/static/chunks/framework-9b5d6ec4444c80fa.js:11:95384)
    at hj (https://discordpackage.com/_next/static/chunks/framework-9b5d6ec4444c80fa.js:11:95647)
    at hi (https://discordpackage.com/_next/static/chunks/framework-9b5d6ec4444c80fa.js:11:95534)
    at hj (https://discordpackage.com/_next/static/chunks/framework-9b5d6ec4444c80fa.js:11:96964)
    at hi (https://discordpackage.com/_next/static/chunks/framework-9b5d6ec4444c80fa.js:11:95534)
    at hj (https://discordpackage.com/_next/static/chunks/framework-9b5d6ec4444c80fa.js:11:95782)
    at hi (https://discordpackage.com/_next/static/chunks/framework-9b5d6ec4444c80fa.js:11:95534)
    at hj (https://discordpackage.com/_next/static/chunks/framework-9b5d6ec4444c80fa.js:11:95844)
    at hi (https://discordpackage.com/_next/static/chunks/framework-9b5d6ec4444c80fa.js:11:95534)
``` 
```
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at hg (https://discordpackage.com/_next/static/chunks/framework-9b5d6ec4444c80fa.js:11:94139)
    at hi (https://discordpackage.com/_next/static/chunks/framework-9b5d6ec4444c80fa.js:11:95384)
    at hj (https://discordpackage.com/_next/static/chunks/framework-9b5d6ec4444c80fa.js:11:95647)
    at hi (https://discordpackage.com/_next/static/chunks/framework-9b5d6ec4444c80fa.js:11:95534)
    at hj (https://discordpackage.com/_next/static/chunks/framework-9b5d6ec4444c80fa.js:11:96964)
    at hi (https://discordpackage.com/_next/static/chunks/framework-9b5d6ec4444c80fa.js:11:95534)
    at hj (https://discordpackage.com/_next/static/chunks/framework-9b5d6ec4444c80fa.js:11:95782)
    at hi (https://discordpackage.com/_next/static/chunks/framework-9b5d6ec4444c80fa.js:11:95534)
    at hj (https://discordpackage.com/_next/static/chunks/framework-9b5d6ec4444c80fa.js:11:95844)
    at hi (https://discordpackage.com/_next/static/chunks/framework-9b5d6ec4444c80fa.js:11:95534)
```

**Comment by peterhanania** [comment]
Hi, please join the discord server https://discordpackage.com/discord
